name: Populate Workflows

on:
  workflow_dispatch:
    inputs:
      target-repo:
        description: 'Target repository name'
        required: true
        default: 'crru-jira-to-ado'
        type: string

permissions:
  contents: write
  packages: write

jobs:
  populate-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Get target repository name
      id: vars
      run: echo "TARGET_REPO=${{ github.event.inputs['target-repo'] }}" >> $GITHUB_ENV

    - name: Clone target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/${{ env.TARGET_REPO }}
        ref: main        
        token: ${{ secrets.MY_TOKEN }}
        sparse-checkout: '.github/workflows'
        persist-credentials: false
        path: target-repo

    - name: Copy workflows to target repository
      run: |
        cp -r .github/workflows/my-workflows/* target-repo/.github/workflows/

    - name: Commit changes
      run: |
        cd target-repo
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Populate workflows from source repository"

    - name: Push changes      
      run: |
        cd target-repo
        git push https://${{ secrets.MY_TOKEN }}@github.com/${{ github.repository_owner }}/${{ env.TARGET_REPO }}

    - name: Clean up
      run: |
        rm -rf target-repo